name: Deploy to Nuget

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenActive.NET
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Setup .NET Core 2.1.808
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.808

      - name: Install dependencies
        run: dotnet restore
        
      - name: Test
        run: dotnet test ./OpenActive.NET.Test/OpenActive.NET.Test.csproj --configuration Release --no-restore --verbosity normal
        
      - name: Build
        run: dotnet build ./OpenActive.NET/OpenActive.NET.csproj --configuration Release --no-restore
        
      - name: Pack
        run: dotnet pack  ./OpenActive.NET/OpenActive.NET.csproj --include-symbols --include-source --no-build
        
      - name: Push to Nuget
        run: dotnet nuget push "./OpenActive.NET/**/*.nupkg" -k ${{secrets.NUGET_API_KEY}}
        
